### ISSUE TITLE
Volume for configuration

### ISSUE THREAD

**Issue by roly445** [Technosoft2000/docker-calibre-web#13]
Is it possible to map the configuration to the file system instead of internally inside the container.  I have just updated the image and lost all the configuration.

**Comment by Technosoft2000** [comment]
Hi,

the Calibre Web configuration is stored at **app.db** and **gdrive.db** and both files are written to the mapped _/books_ volume next to the Calibre **metadata.db**, but if no write access exists on the mapped _/books_ volume for the container user then the configuration stays in the container. Please check also your passed _PUID_ and _PGID_ values. Nevertheless it would be great if you could provide the log output so that I can help you in detail.

In addition I'll also think about how to support an optional configuration volume.

**Comment by roly445** [comment]
The next time it happens I'll grab the logs.  I didn't know it happened until someone told me as I use WatchTower to update my docker images.

I see the the config now,  I'm not sure why it wasn't there originally.   With all that said, it would still be nice to hold the config somewhere differently from the books as for me that's a network share.

**Comment by Technosoft2000** [comment]
A new version 1.1.10 is available with support of a dedicated configuration directory - here an example:

```
docker create --name=calibre-web --restart=always \
-v /volume1/books/calibre:/books \
-v /volume1/docker/apps/calibre-web/config:/calibre-web/config \
-e USE_CONFIG_DIR=true \
-e SET_CONTAINER_TIMEZONE=true \
-e CONTAINER_TIMEZONE=Europe/Vienna \
-e PGID=65539 -e PUID=1029 \
-p 8083:8083 \
technosoft2000/calibre-web
```
