### ISSUE TITLE
Hide books from login screen

### ISSUE THREAD

**Issue by vincowl** [Technosoft2000/docker-calibre-web#15]
Is it possible to hide books before signing in ? Then I would be able to have a fully hidden content to non authorized users. Right now, anonymous user can have a look at the library content, but cannot have access to descriptions or books themselves.

**Comment by Technosoft2000** [comment]
Hi @vincowl,

I've recreated my container and got the actual Calibre-Web sources from [janeczku/calibre-web](https://github.com/janeczku/calibre-web/) commit _9182d8912816c27e67e452334df370c8fdc89ba4_ and I don't see any books before signing in.

Btw. this question has nothing to do with the Docker Container, it's application related ;)

Goto the **Basic Configuration** site and check if the following option is deactivated:
_Enable anonymous browsing_

Because by default this option is active and the admin has to deactivate this feature.

Regarding Calibre-Web application related questions and issues please check & goto [janeczku/calibre-web](https://github.com/janeczku/calibre-web/) in future.

Thanks
TS2k

**Comment by vincowl** [comment]
Indeed, it works... Strange !.... Sorry for this wrong issue. Maybe web browser's cache not cleared...

**Comment by vincowl** [comment]
Indeed, it works... Strange !.... Sorry for this wrong issue. Maybe web browser's cache not cleared...
