### ISSUE TITLE
Can't change metadata related with path / filename

### ISSUE THREAD

**Issue by klabog** [Technosoft2000/docker-calibre-web#41]
When I try to change metadata related with file name (path) like author or Title I get an error like this: 
`Rename author from: '/books/unknown/20180915_Lavavajillas_Manual_925321ES (8960)' to '/books/AEG/20180915_Lavavajillas_Manual_925321ES (8960)' failed with error: [Errno 2] No such file or directory`
There should be a way to rename books or authors like in the original calibre because almost every time you touch metadata there are changes in title or authors. 
If you don't touch those fields but others you don't get this error.
I have configured the docker with 
PGROUP | 100 
PUSER | 1000
wich are admin user and administrator group, but noticed, that some directories for example the Calibre Web application folder is changed to user docker.
Any help appreciated.
Klaus
![bildschirmfoto vom 2018-11-02 15-35-20](https://user-images.githubusercontent.com/6863300/47922925-78647b80-deb8-11e8-97a3-b36670321ddb.png)

**Comment by Technosoft2000** [comment]
Hi @klabog,

sorry for the late answer, I'll try to check & reproduce the issue locally and give you feedback as soon as possible.

**Comment by Technosoft2000** [comment]
Hi @klabog,

I've tested different books and changed metadata related with file name (path) like author or title and it works like expected.

I've tested this issue with two Calibre-Web versions:
  * commit timestamp: 9/9/18, 5:17 PM
  * commit timestamp: 11/25/18, 1:29 PM (latest one)

I assume that the permissions on the `/books` mapping are not correct.

Please have a look at the docker container log and at the calibre-web.log.
In addition try to connect into the docker container and then change into the `/books` directory and try to create a directory and file.

**Comment by Technosoft2000** [comment]
In my case I've found that the directory of the book was at Calibre Database not the same as on the filesystem => Data Inconsistency, and Calibre Web tried then to rename a directory which doesn't exist.
In my case:
 * Calibre Database deliver: **Perry Rhodan Neo 012_ Tod unter fremder  (38)**
 * On filesystem it was: **Perry Rhodan Neo 012_ Tod unter fremder**

I remember that I've added this book via the original Calibre Application on Windows, so in my case the original application created this issue.

Btw. the issue is not related to the Docker Container, it is an application issue but I've no idea how Calibre Web should manage or handle such Data Inconsistency in an automatic way.

In my case I've looked also into the **calibre-web.log** file and got this error message like the one on the web UI:
```
[2018-11-25 20:26:18,054] {/calibre-web/app/cps/helper.py:288} ERROR - Rename title from: /books/Marc A. Herren/Perry Rhodan Neo 012_ Tod unter fremder  (38) to /books/Marc A. Herren/Perry Rhodan Neo 012 - Tod unter fremder Sonne (38): [Errno 2] No such file or directory
```

Then I've changed the existing name of directory **Perry Rhodan Neo 012_ Tod unter fremder** to the one which Calibre-Web reads from the Database **Perry Rhodan Neo 012_ Tod unter fremder  (38)** and afterwards the change of the Metadata on the Web UI works as epected.

Hope it helps you too :)

**Comment by klabog** [comment]
[20181126_Techno_Log_direktnachInstall.pdf](https://github.com/Technosoft2000/docker-calibre-web/files/2621596/20181126_Techno_Log_direktnachInstall.pdf)
[20181126_Techno_Net.pdf](https://github.com/Technosoft2000/docker-calibre-web/files/2621597/20181126_Techno_Net.pdf)
[20181126_Techno_Umgebung.pdf](https://github.com/Technosoft2000/docker-calibre-web/files/2621598/20181126_Techno_Umgebung.pdf)
[20181126_Techno_Freigaben.pdf](https://github.com/Technosoft2000/docker-calibre-web/files/2621599/20181126_Techno_Freigaben.pdf)

I have to confess that I do not have much knowledge about Docker. If I get hints on how to do something I'll give you more information about my installation.
I have now re-installed the container (Qnap does not allow changes in the advanced settings without re-installing the container) and send you the installation log, my environment, network and share settings.
What amazes me is that even though I set the permissions for group and user in the settings to administrators and admin respectively, the directories of app, kindlegen, and config get the User Docker and the group Everyone during the installation. books is not changed and stays with the existing settings (admin / administrators).
If more information is needed, then I ask for step by step instructions how to find them.
