### ISSUE TITLE
Dockerfile for a different linux distribution

### ISSUE THREAD

**Issue by paulhybryant** [Technosoft2000/docker-calibre-web#44]
The dockerfile here used alphine, which unfortunately don't have a calibre package in its package list.
It is very complex to build all dependencies of calibre and the binary from source code. It would be really helpful if a dockerfile for other linux distributions such as ubuntu / archlinux can be provided.
That way, I can simply install the compiled binary from the package manager.

Currently calibre releases only contains binary distribution for x86 cpu, not arm cpu. I am trying to deploy calibre-web on a device with arm cpu. 

Thanks!

**Comment by Technosoft2000** [comment]
> The dockerfile here used alphine, which unfortunately don't have a calibre package in its package list.

Correct, because they don't have a maintainer yet for it, and such a thing could be really time consuming.

> It is very complex to build all dependencies of calibre and the binary from source code.

I agree with you, because I tried it already for my docker image and I failed yet.
I wanted to compile it by myself so that I can provide later an ARM build of the docker image too.

> ... for other linux distributions such as ubuntu / archlinux ...

Originally I started with an Ubuntu base image but I detected issues while running python applications with it which weren't solvable. Then I've chosen Alpine because it delivers a minimalistic system without any ballast which is much better for docker containers.

Btw. I don't have so much spare time to maintain different versions.

But feel free to fork https://github.com/Technosoft2000/docker-alpine-base and https://github.com/Technosoft2000/docker-calibre-web to create your own image.

Linuxserver.io provides a docker image for 
 * ARM - https://hub.docker.com/r/lsioarmhf/calibre-web/
 * ARM 64bit - https://hub.docker.com/r/lsioarmhf/calibre-web-aarch64/
which is without calibre and kindlegen.

> ... I can simply install the compiled binary from the package manager.

Understandable - see https://calibre-ebook.com/download_linux - which says: _"Please do not use your distribution provided calibre package, as those are often buggy/outdated. Instead use the Binary install described below."_

On the other side there is also that info: _"WARNING: calibre is a highly complex piece of software with lots of very finicky dependencies. If you install from source, you are on your own. Please do not open bug reports or expect any form of support. You have been warned."_

So the situation is not that easy.

**Comment by Technosoft2000** [comment]
> Just to clarify, the dependency on calibre is just for book conversion, is it?

Correct, so without the original calibre or kindlegen there is no book conversion possible.

**Comment by paulhybryant** [comment]
Just FYI, I tried to follow the instruction from the official guide here
https://github.com/kovidgoyal/build-calibre
and after fixing some issues, the calibre dependencies can be built with the following docker configuration
https://github.com/paulhybryant/docker-calibre

**Comment by Technosoft2000** [comment]
Hi @paulhybryant,

thanks for the information, I knew that already and tried it already once on Alpine but it didn't worked.
But I'll take your dockerfile as input for another try :)

One difference between Ubuntu and Alpine are the C libraries - Ubuntu uses **glibc** and Apline uses **musl libc**.

**Comment by paulhybryant** [comment]
No problem. I just realized that my docker file is not complete yet.
The current version only covers the bootstrap step:
python setup.py bootstrap

I am updating the Dockerfile for the compilation step (per the build-calibre guide).

**Comment by aptalca** [comment]
Just an update, the linuxserver images are now multi-arch, so you can just pull `linuxserver/calibre-web` and you'll automatically get the correct arch image for your system (x86_64, armhf or aarch64).

Also, I have a personal rdp calibre image here: https://hub.docker.com/r/aptalca/docker-rdp-calibre
It's a little clunky, but it works for getting a calibre database set up

**Comment by paulhybryant** [comment]
Thanks @aptalca , that is good to know.
AFAIK calibre only has binary release for x86 arch,
did you build your own version from source?

**Comment by paulhybryant** [comment]
Just tried that image and it is nice. Can you also share the Dockerfile used to create the image?
It would be useful for other application as well.
Thanks!
