### ISSUE TITLE
azw3  book can not send to kindle

### ISSUE THREAD

**Issue by fel835** [Technosoft2000/docker-calibre-web#62]
azw3 book can not send to kindle
![xxx](https://user-images.githubusercontent.com/2617716/60318401-74d0b800-99a5-11e9-938f-4abf4398ed53.png)

**Comment by Technosoft2000** [comment]
This is a restriction of the Calibre Web application itself and has nothing to do with the Docker image/container. Please go to the Calibre Web application project https://github.com/janeczku/calibre-web/ and create there the ticket, because I'm not the developer of Calibre Web, I only provide a Docker image which can run the Calibre Web application.

**Comment by OzzieIsaacs** [comment]
This was reported and discussed in janeczku/calibre-web#816. 
As far as I understood it, azw3 is not supported by amazon to send to the kindle, so the feature was implemented and is meanwhile removed again.

**Comment by Technosoft2000** [comment]
Thanks for the clarification @OzzieIsaacs - maybe it is possible to convert from azw3 to mobi with the precondition that the azw3 file doesn't have any DRM.

**Comment by OzzieIsaacs** [comment]
Good idea, it's now implemented.
![grafik](https://user-images.githubusercontent.com/6438895/70866550-6d10ca00-1f6b-11ea-926d-d811312e4ae2.png)

**Comment by Technosoft2000** [comment]
Ohhh wow that's so great, thanks for the fast implementation :D +1

**Comment by Technosoft2000** [comment]
Closed because the issue was fixed with an enhancement at Calibre-Web.
