### ISSUE TITLE
Modifying Metadata in Calibre-web doesn't work for Synology docker.

### ISSUE THREAD

**Issue by abubaman** [Technosoft2000/docker-calibre-web#75]
I am a user who loves calibre-web and appreciate for techosoft2000's docker image.

Almost all function works fine if I use calibre-web as a read-only version which means that I could find problem only when I modify metadata on calibre-web or read status change on calibre-web.

If I change metadata or something on calibre-web, it doesn't sync to real calibre library which I can check in Calibre program which is installed in windows system connected to the calibre library with Cloud Station(by Synology).

I perfectly followed your instruction (making docker user/group, PUID/PGID/Time zone/Config DIR Setting, folder permission, folder owner, etc.) but it is not working.
But, I found that it works sometimes when I change the permission of Calibre-library folder(and its child folder and file) but it just work once when I change the permission of them.

So, I think it could be a permission problem but I have no idea because I followed perfectly your instruction and I tried to do many things like changing user(docker->admin) and so on. So, please let me know if you have any ideas.

And one more question. When I type 'id docker' in my Synology ssh, it shows below
uid=1048(docker), gid=100(users) groups=100(users), 101(administrators), 65539(docker)
PUID is clear but what is the PGID which I need to use? now, I am using 65539(docker)

And in Synology docker setting, I can find PUSER, PGROUP which is set 'calibre' both.
I tried to both it let be 'calibre' or change to 'docker' but it doesn't work also. what does those mean of PUSER and PGROUP and what do I need to set the name of PUSER and PGROUP?

**Comment by Technosoft2000** [comment]
> ... connected to the calibre library with Cloud Station(by Synology).
I've never tried to sync the calibre library with Cloud Station, so can't say which impact this could have.

> I perfectly followed your instruction ...
I've set it once here locally on my Synology NAS without any issue as I remember.
Maybe it's a side effect of the usage with Cloud Station, no idea.

> So, I think it could be a permission problem ...
Yes seems so.

> PGID
I use here 100 so that new files will be created with this GID on the NAS filesystem

>  I can find PUSER, PGROUP which is set 'calibre' both.
This are the names which are used inside the docker container, and they will be created with the assigned PUID and PGID, please don't modify them after the creation of the container, because otherwise it could result into unknown issues.
