### ISSUE TITLE
metadata.db

### ISSUE THREAD

**Issue by vincentHuangZhen** [Technosoft2000/docker-calibre-web#8]
In Synology，failed to launch, no metadata.db file.

In advanced Settings:
File directory: /books/calibre
Load path: /volume1/books/calibre

[ERROR] The mapped volume for /books doesn't contain a Calibre database file 'metadata.db'
\> Please fix the volume mapping before you retry to start the container again
\> Stopping the container with errorlevel 1

**Comment by Technosoft2000** [comment]
Please provide more detailed information:
 * which container creation command did you used (including all mappings, env. settings, ...)
 * did you mapped _/volume1/books/calibre_ as _/books_ as described in the description, because then you have to use only _/books_ as directory instead of _/books/calibre_
* does _/volume1/books/calibre_ contain already a **metadata.db** from Calibre, or was Calibre never used before

**Comment by vincentHuangZhen** [comment]
* I used Synology Docker to automatically install it.
* The directory '/volume1/books/calibre' is empty. Calibre has not been successfully run.

**Comment by Technosoft2000** [comment]
> I used Synology Docker to automatically install it.

What means in your case _automatically_ - because after pulling/downloading the image you have to configure the volume paths, the environment setting, the port mapping of the container in the Synology Docker Web Interface before you can run it successfully. When you launch the container over the Synology Docker Web Interface then you have to press the 'Advanced Settings' button to have the possibility to setup the needed configuration, see also https://www.synology.com/en-global/knowledgebase/DSM/help/Docker/docker_container

> The directory '/volume1/books/calibre' is empty.

You need an existing directory which already contains books and the library database **metadata.db** from the software Calibre => https://calibre-ebook.com/ - this is a pre-requirement to successfully run the Calibre-Web application from https://github.com/janeczku/calibre-web
This docker container only provides the environment to successfully run the Calibre-Web application

**Comment by vincentHuangZhen** [comment]
Thanks your reply :) I'll try it.
