### ISSUE TITLE
chinese is not a valid language

### ISSUE THREAD

**Issue by Alex520Wang** [Technosoft2000/docker-calibre-web#80]
装了新版本后，上传新书时会出现chinese is not a valid language提示。语言栏设置已经修改过了，就是编辑书本元数据时，内容专辑栏那一块的菜单是英文的，其他是中文显示正常，装以前的旧版本没出现这个问题。

还有，这一版加的Identifiers有什么用处？新用户把Identifiers value值的书籍设成了限制，但该书还是可以可见，按照以前的版本通过标签栏来限制查看倒是可以。

**Comment by Technosoft2000** [comment]
Please write in English - I've translated your text with Google Translate:

> After installing the new version, the Chinese is not a valid language prompt will appear when uploading a new book. The language bar settings have been modified, that is, when editing the book metadata, the menu of the piece of the content album bar is in English, and the other is displayed normally in Chinese. This problem does not appear before installing the old version.
> 
> Also, what is the use of Identifiers added in this edition? The new user has set a limit to the Identifiers value book, but the book can still be seen, according to the previous version through the tab bar to limit viewing is OK.

It seems that your issue isn't related to the docker image, because you describe an application issue.
The application Calibre-Web is developed here https://github.com/janeczku/calibre-web and any issue related to the application must be reported there.
