### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'restrict_modal' is undefined

### ISSUE THREAD

**Issue by Irv007** [Technosoft2000/docker-calibre-web#85]
Good Morning,

Since having updated to calibre-web 0.6.8 yesterday, I can't perform some actions using gui.
I'm getting the follogin error: jinja2.exceptions.UndefinedError: 'restrict_modal' is undefined
Please see the attached /app/calibre-web/calibre-web.log below for Details.

This error occurs on several occasions.
E. g.:
- clicking on user name in "Benutzerliste"
- clicking on "admin" in the upper right corner
- clicking on "Benutzeroberflächenkonfiguration"

I'm running Calbire Web on Docker on Ubuntu.

Can somebody help?

with best regards
Irvin

/app/calibre-web/calibre-web.log: see attached file
[calibre-web.log](https://github.com/Technosoft2000/docker-calibre-web/files/5011762/calibre-web.log)
:

**Comment by Irv007** [comment]
ups. I#m runng linuxserver/calibre-web at the moment, not technosoft2000/calibre-web.

**Comment by Technosoft2000** [comment]
Hi @Irv007 

it seems that you don't use my docker container because my one comes with the following Python Version (info from the Calibre-Web About page)

**Python | 2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**

but in your attached log the Calibre-Web uses a Python 3.6 version - here a cutout from your log

`/usr/local/lib/python3.6/dist-packages`
